import { useState } from "react";
import SupervisorIcon from "../components/SupervisorIcon.jsx";

const tabs = [["profile", "Profile", "user"], ["security", "Security", "shield"], ["notifications", "Notifications", "mail"], ["system", "System", "gear"], ["access", "Access Control", "lock"]];

function Settings() {
  const [activeTab, setActiveTab] = useState("profile");
  const [saved, setSaved] = useState(false);
  const [profile, setProfile] = useState({ name: "Supervisor", age: "", gender: "", email: "", phone: "" });
  const save = (event) => { event.preventDefault(); setSaved(true); window.setTimeout(() => setSaved(false), 2200); };
  return <>
    <div className="supervisor-page-heading"><div><p className="supervisor-eyebrow">Account</p><h1>Profile</h1><p className="supervisor-subtitle">View and manage your profile details.</p></div><span className="supervisor-live-badge"><i /> Secure workspace</span></div>
    <div className="settings-layout"><aside className="supervisor-panel settings-tabs" aria-label="Settings sections">{tabs.map(([id, label, icon]) => <button className={activeTab === id ? "active" : ""} type="button" key={id} onClick={() => setActiveTab(id)}><SupervisorIcon name={icon} size={17} /><span>{label}</span></button>)}</aside><section className="supervisor-panel settings-content"><div className="supervisor-panel-heading"><div><p className="supervisor-eyebrow">{tabs.find(([id]) => id === activeTab)?.[1]}</p><h2>{activeTab === "profile" ? "Profile details" : tabs.find(([id]) => id === activeTab)?.[1]}</h2></div>{saved && <span className="save-message"><SupervisorIcon name="check" size={14} /> Changes saved</span>}</div>{activeTab === "profile" && <form className="supervisor-form" onSubmit={save}><div className="profile-header"><div className="profile-avatar"><SupervisorIcon name="user" size={26} /></div><div><strong>Supervisor profile</strong><p>Keep your account details up to date.</p></div></div><div className="form-grid"><label>Name<input value={profile.name} onChange={(event) => setProfile({ ...profile, name: event.target.value })} /></label><label>Age<input type="number" value={profile.age} onChange={(event) => setProfile({ ...profile, age: event.target.value })} placeholder="Add age" /></label><label>Gender<select value={profile.gender} onChange={(event) => setProfile({ ...profile, gender: event.target.value })}><option value="">Select gender</option><option>Male</option><option>Female</option><option>Other</option></select></label><label>Gmail ID<input type="email" value={profile.email} onChange={(event) => setProfile({ ...profile, email: event.target.value })} placeholder="supervisor@gmail.com" /></label><label>Phone Number<input value={profile.phone} onChange={(event) => setProfile({ ...profile, phone: event.target.value })} placeholder="Add phone number" /></label></div><div className="form-actions"><button className="supervisor-outline-button" type="button">Logout</button><button className="supervisor-primary-button" type="submit">Save Changes</button></div></form>}{activeTab === "security" && <SettingsForm title="Security Settings" fields={["Current Password", "New Password", "Confirm Password"]} type="password" onSave={save} />}{activeTab === "notifications" && <SettingsToggles title="Notification Preferences" items={["Email Notifications", "User Activity Alerts", "System Updates"]} onSave={save} />}{activeTab === "system" && <SettingsForm title="System Configuration" fields={["Company name", "Timezone", "Date format", "Session timeout"]} onSave={save} />}{activeTab === "access" && <SettingsToggles title="Access Control" items={["Two-Factor Authentication", "IP Whitelist", "Failed Login Lockout", "Password Complexity"]} onSave={save} />}</section></div>
  </>;
}

function SettingsForm({ fields, type = "text", onSave }) { return <form className="supervisor-form" onSubmit={onSave}><div className="settings-form-list">{fields.map((field) => <label key={field}>{field}<input type={type} placeholder={field === "Timezone" ? "Asia/Calcutta" : field === "Date format" ? "DD-MM-YYYY" : field === "Session timeout" ? "30" : `Enter ${field.toLowerCase()}`} /></label>)}</div><div className="form-actions"><button className="supervisor-outline-button" type="button">Reset</button><button className="supervisor-primary-button" type="submit">Save Settings</button></div></form>; }
function SettingsToggles({ items, onSave }) { return <form className="supervisor-form" onSubmit={onSave}><div className="settings-toggle-list">{items.map((item, index) => <label className="settings-toggle" key={item}><span><strong>{item}</strong><small>Control this workspace preference.</small></span><input type="checkbox" defaultChecked={index !== 2} /><i /></label>)}</div><button className="supervisor-primary-button" type="submit">Save Preferences</button></form>; }

export default Settings;
