import { useMemo, useState } from "react";
import SupervisorIcon from "../components/SupervisorIcon.jsx";
import SupervisorModal from "../components/SupervisorModal.jsx";
import SupervisorTable from "../components/SupervisorTable.jsx";

const emptyForm = { name: "", email: "", password: "", role: "Employee", companyId: "", phone: "", department: "", specialization: "", experience: "" };

function UserManagement({ users, companies, onAddUser }) {
  const [query, setQuery] = useState("");
  const [role, setRole] = useState("All roles");
  const [showModal, setShowModal] = useState(false);
  const [form, setForm] = useState(emptyForm);
  const [formError, setFormError] = useState("");
  const filteredUsers = useMemo(() => users.filter((user) => (role === "All roles" || user.role === role) && `${user.name} ${user.email} ${user.company}`.toLowerCase().includes(query.toLowerCase())), [users, query, role]);
  const submit = async (event) => { event.preventDefault(); setFormError(""); try { await onAddUser(form); setForm(emptyForm); setShowModal(false); } catch (error) { setFormError(error.message || "The user could not be created."); } };
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const columns = [{ key: "name", label: "User", render: (row) => <div className="table-user"><span>{row.name.slice(0, 1)}</span><div><strong>{row.name}</strong><small>{row.email}</small></div></div> }, { key: "role", label: "Role", render: (row) => <span className="role-pill">{row.role}</span> }, { key: "company", label: "Company" }, { key: "status", label: "Status", render: (row) => <span className={`status-pill status-${row.status.toLowerCase()}`}>{row.status}</span> }, { key: "lastActive", label: "Last active" }];
  return <>
    <div className="supervisor-page-heading"><div><p className="supervisor-eyebrow">User Directory</p><h1>User Management</h1><p className="supervisor-subtitle">Manage the people who keep each wellness workspace moving.</p></div><button className="supervisor-primary-button" type="button" onClick={() => setShowModal(true)}><SupervisorIcon name="plus" size={17} /> Add User</button></div>
    <section className="supervisor-toolbar supervisor-panel"><div className="supervisor-search"><SupervisorIcon name="user" size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search users" aria-label="Search users" /></div><select value={role} onChange={(event) => setRole(event.target.value)} aria-label="Filter by role"><option>All roles</option><option>Employee</option><option>HR</option><option>Wellness Expert</option></select><span className="toolbar-count">{filteredUsers.length} users</span></section>
    <section className="supervisor-panel supervisor-table-panel"><div className="supervisor-panel-heading"><div><p className="supervisor-eyebrow">Accounts</p><h2>Workspace users</h2></div><button className="supervisor-outline-button" type="button" onClick={() => { setQuery(""); setRole("All roles"); }}>Clear filters</button></div><SupervisorTable columns={columns} rows={filteredUsers} emptyMessage="No users match your filters." /></section>
    {showModal && <SupervisorModal title="Add User" description="Create an account with the role and company details used across the workspace." onClose={() => setShowModal(false)}><form className="supervisor-form" onSubmit={submit}>{formError && <p className="form-error">{formError}</p>}<div className="form-grid"><label>Name<input required value={form.name} onChange={(event) => update("name", event.target.value)} placeholder="Enter full name" /></label><label>Email<input required type="email" value={form.email} onChange={(event) => update("email", event.target.value)} placeholder="Enter Gmail address" /></label><label>Password<input required minLength={6} type="password" value={form.password} onChange={(event) => update("password", event.target.value)} placeholder="At least 6 characters" /></label><label>Role<select value={form.role} onChange={(event) => update("role", event.target.value)}><option>Employee</option><option>HR</option><option>Wellness Expert</option></select></label><label>Company<select required value={form.companyId} onChange={(event) => update("companyId", event.target.value)}><option value="">Select company</option>{companies.map((company) => <option value={company.id} key={company.id}>{company.name}</option>)}</select></label><label>Phone<input value={form.phone} onChange={(event) => update("phone", event.target.value)} placeholder="Optional phone number" /></label>{form.role === "Employee" && <label>Department<input required value={form.department} onChange={(event) => update("department", event.target.value)} placeholder="Engineering, HR, etc." /></label>}{form.role === "Wellness Expert" && <><label>Specialization<input required value={form.specialization} onChange={(event) => update("specialization", event.target.value)} placeholder="Nutritionist, psychologist, etc." /></label><label>Experience<input required value={form.experience} onChange={(event) => update("experience", event.target.value)} placeholder="Years of experience" /></label></>}</div><div className="form-actions"><button className="supervisor-outline-button" type="button" onClick={() => setShowModal(false)}>Cancel</button><button className="supervisor-primary-button" type="submit">Add User</button></div></form></SupervisorModal>}
  </>;
}

export default UserManagement;
